import { execFile } from 'child_process';
import * as path from 'path';
import { promisify } from 'util';
import { LAMBDA_NODE_OPTIONS } from '../lib/lambda.js';
import { LAUNCHD_LABEL, type ScheduleConfig } from './config.js';

const execFileAsync = promisify(execFile);

/**
 * The LaunchDaemon and the wake schedule (macOS facts: scratchpad/scripts-overhaul/M5-mac-automation.md).
 *
 * - A LaunchDaemon (not a LaunchAgent) runs with nobody logged in. `UserName` runs it as the
 *   developer's user, so it uses their files and `.env.automation`.
 * - `StartCalendarInterval`: if the Mac is asleep at that time, launchd runs the job on the
 *   next wake; if it's off, it doesn't run. launchd never starts a second copy.
 * - launchd gives jobs a minimal environment, so PATH and HOME are set explicitly, and node
 *   is an absolute path.
 * - `ProcessType: Interactive`: no CPU/IO throttling. Unset (or Standard), launchd applies
 *   "light resource limits", which would slow hours of transcription.
 * - `ExitTimeOut`: seconds launchd waits after SIGTERM (bootout) before SIGKILL; the run
 *   needs time to stop whisper workers and write its record.
 */

export interface PlistInput extends Pick<ScheduleConfig, 'runnerDir' | 'hour' | 'minute' | 'nodePath' | 'userName'> {
  homeDir: string;
  logPath: string;
}

export function launchdPath(nodePath: string): string {
  const dirs = [path.dirname(nodePath), '/opt/homebrew/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin'];
  return [...new Set(dirs)].join(':');
}

export function renderLaunchDaemonPlist(input: PlistInput): string {
  const string = (value: string) => `<string>${escapeXml(value)}</string>`;
  const env: Record<string, string> = {
    PATH: launchdPath(input.nodePath),
    HOME: input.homeDir,
    USER: input.userName,
    LANG: 'en_US.UTF-8',
    NODE_OPTIONS: LAMBDA_NODE_OPTIONS,
    // pnpm comes from Corepack; never wait on its download prompt
    COREPACK_ENABLE_DOWNLOAD_PROMPT: '0',
  };
  // Keep folder overrides (used for testing) the same for the scheduled job
  for (const key of ['BDS_LOGS_DIR', 'BDS_APP_SUPPORT_DIR']) {
    if (process.env[key]) env[key] = process.env[key]!;
  }
  const args = [
    input.nodePath,
    path.join(input.runnerDir, 'node_modules/tsx/dist/cli.mjs'),
    path.join(input.runnerDir, 'scripts/cli/index.ts'),
    'schedule',
    'run',
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by \`pnpm bds schedule install\`; re-run it to change. Removed by \`bds schedule uninstall\`. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  ${string(LAUNCHD_LABEL)}
  <key>UserName</key>
  ${string(input.userName)}
  <key>ProgramArguments</key>
  <array>
${args.map(arg => `    ${string(arg)}`).join('\n')}
  </array>
  <key>WorkingDirectory</key>
  ${string(input.runnerDir)}
  <key>EnvironmentVariables</key>
  <dict>
${Object.entries(env).map(([key, value]) => `    <key>${key}</key>\n    ${string(value)}`).join('\n')}
  </dict>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>${input.hour}</integer>
    <key>Minute</key>
    <integer>${input.minute}</integer>
  </dict>
  <key>RunAtLoad</key>
  <false/>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>ExitTimeOut</key>
  <integer>60</integer>
  <key>StandardOutPath</key>
  ${string(input.logPath)}
  <key>StandardErrorPath</key>
  ${string(input.logPath)}
</dict>
</plist>
`;
}

function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/** Parse `--at=HH:MM` (24-hour, local time). */
export function parseTimeOfDay(value: string): { hour: number; minute: number } | null {
  const match = value.match(/^(\d{1,2}):(\d{2})$/);
  if (!match) return null;
  const hour = Number(match[1]);
  const minute = Number(match[2]);
  return hour < 24 && minute < 60 ? { hour, minute } : null;
}

export function formatTimeOfDay(hour: number, minute: number, second?: number): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${pad(hour)}:${pad(minute)}${second === undefined ? '' : `:${pad(second)}`}`;
}

/** The daily wake time, `minutesBefore` the run (wrapping past midnight). */
export function wakeTime(hour: number, minute: number, minutesBefore: number): { hour: number; minute: number } {
  const total = (((hour * 60 + minute - minutesBefore) % 1440) + 1440) % 1440;
  return { hour: Math.floor(total / 60), minute: total % 60 };
}

/** `pmset repeat …` arguments for a daily wake (or power on) at that time. */
export function pmsetRepeatArgs(hour: number, minute: number): string[] {
  return ['repeat', 'wakeorpoweron', 'MTWRFSU', formatTimeOfDay(hour, minute, 0)];
}

/** The next time a daily job at hour:minute (local time) runs after `now`. */
export function nextRunAfter(now: Date, hour: number, minute: number): Date {
  const next = new Date(now);
  next.setHours(hour, minute, 0, 0);
  if (next <= now) next.setDate(next.getDate() + 1);
  return next;
}

export interface LaunchdJobState {
  loaded: boolean;
  state?: string;
  runs?: number;
  lastExitCode?: string;
  pid?: number;
}

/** Parse `launchctl print system/<label>` (fields are informal and may change between macOS versions). */
export function parseLaunchctlPrint(output: string): LaunchdJobState {
  if (!/= \{/.test(output)) return { loaded: false };
  const field = (name: string) => output.match(new RegExp(`^\\s*${name} = (.+)$`, 'm'))?.[1].trim();
  const runs = field('runs');
  const pid = field('pid');
  return {
    loaded: true,
    state: field('state'),
    runs: runs ? Number(runs) : undefined,
    lastExitCode: field('last exit code'),
    pid: pid ? Number(pid) : undefined,
  };
}

export async function launchdJobState(): Promise<LaunchdJobState> {
  try {
    const { stdout } = await execFileAsync('/bin/launchctl', ['print', `system/${LAUNCHD_LABEL}`]);
    return parseLaunchctlPrint(stdout);
  } catch {
    return { loaded: false };
  }
}

/** `pmset -g sched`, trimmed ('' when nothing is scheduled). */
export async function pmsetSchedule(): Promise<string> {
  try {
    const { stdout } = await execFileAsync('/usr/bin/pmset', ['-g', 'sched']);
    return stdout.trim();
  } catch {
    return '';
  }
}

/** The repeating events in `pmset -g sched` output, e.g. "wakepoweron at 2:55AM every day". */
export function parseRepeatingEvents(schedOutput: string): string[] {
  const lines = schedOutput.split('\n');
  const start = lines.findIndex(line => line.startsWith('Repeating power events'));
  if (start === -1) return [];
  const events: string[] = [];
  for (const line of lines.slice(start + 1)) {
    if (!/^\s/.test(line) || !line.trim()) break;
    events.push(line.trim());
  }
  return events;
}
